<?php

namespace Tests\Feature;

use App\Models\Bom;
use App\Models\Item;
use App\Models\ProcurementOrder;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProcurementManualPoNumberTest extends TestCase
{
    use RefreshDatabase;

    public function test_manual_po_number_can_be_reused_for_multi_supplier_procurement_orders(): void
    {
        $user = User::factory()->create(['role' => User::ROLE_SUPER_ADMIN]);

        $supplierA = Supplier::create(['name' => 'Supplier A']);
        $supplierB = Supplier::create(['name' => 'Supplier B']);

        $itemA = Item::create([
            'sku' => 'HW-MANUAL-PO-A',
            'name' => 'Hardware Manual PO A',
            'unit' => 'pcs',
            'bom_scope' => Bom::TYPE_HARDWARE,
            'created_by' => $user->id,
        ]);

        $itemB = Item::create([
            'sku' => 'HW-MANUAL-PO-B',
            'name' => 'Hardware Manual PO B',
            'unit' => 'pcs',
            'bom_scope' => Bom::TYPE_HARDWARE,
            'created_by' => $user->id,
        ]);

        $poNumber = 'PO-MULTI-SUPPLIER-TEST';

        ProcurementOrder::create([
            'code' => $poNumber,
            'status' => 'submitted',
            'created_by' => $user->id,
        ]);

        $response = $this->actingAs($user)
            ->withHeaders(['X-Requested-With' => 'XMLHttpRequest'])
            ->postJson('/procurement/hardware/orders', [
                'sku_lines' => [
                    [
                        'item_id' => $itemA->id,
                        'quantity' => 3,
                        'unit' => 'pcs',
                    ],
                    [
                        'item_id' => $itemB->id,
                        'quantity' => 7,
                        'unit' => 'pcs',
                    ],
                ],
                'sku_suppliers' => [
                    (string) $itemA->id => $supplierA->id,
                    (string) $itemB->id => $supplierB->id,
                ],
                'po_number' => $poNumber,
                'notes' => 'Manual PO reused for multi supplier test',
            ]);

        $response->assertCreated()
            ->assertJsonPath('message', '2 procurement orders generated by supplier selection.');

        $this->assertSame(3, ProcurementOrder::where('code', $poNumber)->count());

        $this->assertDatabaseHas('procurement_orders', [
            'code' => $poNumber,
            'supplier_id' => $supplierA->id,
            'supplier_name' => 'Supplier A',
            'procurement_scope' => Bom::TYPE_HARDWARE,
        ]);

        $this->assertDatabaseHas('procurement_orders', [
            'code' => $poNumber,
            'supplier_id' => $supplierB->id,
            'supplier_name' => 'Supplier B',
            'procurement_scope' => Bom::TYPE_HARDWARE,
        ]);
    }
}
